---
title: 'T3: A R package for processing tropical tuna fisheries data'
tags:
  - Tuna
  - Species composition
  - surface fisheries
  - Open source software
  - R
authors:
  - name: Mathieu Depetris
    orcid: 0000-0001-8080-0531
    equal-contrib: true
    corresponding: true 
    affiliation: "1, 2" # (Multiple affiliations must be quoted)
  - name: Antoine Duparc
    orcid: 0000-0002-3919-8208
    equal-contrib: true
    corresponding: false 
    affiliation: "1, 2" # (Multiple affiliations must be quoted)
  - name: Pascal Cauquil
    orcid: 0000-0003-0718-8950
    equal-contrib: true
    corresponding: false 
    affiliation: "1, 2" # (Multiple affiliations must be quoted)
  - name: Laurent Floc'h
    orcid: 0000-0003-4764-9766
    equal-contrib: true
    corresponding: false 
    affiliation: "1, 2" # (Multiple affiliations must be quoted)
  - name: Julien Lebranchu
    orcid: 0000-0002-7759-0534
    equal-contrib: true
    corresponding: false
    affiliation: "1, 2" # (Multiple affiliations must be quoted)
affiliations:
 - name: OB7, IRD, Sète, France
   index: 1
 - name: MARBEC, Univ Montpellier, CNRS, IFREMER, IRD, Montpellier, France
   index: 2
#date: 13 August 2017
bibliography: bibliography.bib
# Optional fields if submitting to a AAS journal too, see this blog post:
# https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing
aas-doi: 10.3847/xxxxx <- update this with the DOI from AAS once you know it.
aas-journal: Astrophysical Journal <- The name of the AAS journal.
format: pdf
---

# Summary

The multi-species nature of tropical tuna surface fisheries gives rise to a series of difficulties when estimating the catch by species and catch at size statistics. 
The T3 processing was built about 30 years ago in order to correct biases of the logbook data on species composition and to provide more accurate catch estimates per species for the purse seine fleet, mainly for European and Seychelles fleet.

# Statement of need

European and Seychelles (+ ghana...) scientists need common database design and software for tropical tuna treatment => AVDTH DB and T3 FORTRAN implementation but issue :

* AVDTH DB are local and not shared between fleets, more difficult to manage

* AVDTH DH schema don't handle fish aggregating (or aggregation) device (FAD) description, so the DB used needed to evolve and has been replaced by Observe DB in ? recording more detailed data. 

* Translation of T3 FORTRAN in R [@2018_r_core_team] as t3 R package for Tropical Tuna Treatment. @depetris_mathieu_2022_3878124

# State of the field

Then the t3 R package has known a lot of improvement as 

* the addition of level 3 : species composition correction according to sampling at landing
* documentation

# Software design

design philosophy is based on three core principles: (1) to provide a
user-friendly, modular, object-oriented functions, (2) to use community tools and
standards, (3)

* Model initialization

* Level 1 : logbooks standardization

* Level 2 : samples standardization

* Level 3 : estimation of major tuna species composition 

outputs in .csv 
R6 objects
dplyr for aggregation 

# Research impact statement 

This software and its results is now used by:

* Spanish scientists (IEO)
* Seychelles scientists (SFA)
* French scientists (OB7 + David Kaplan + ...)
* ...

to fill IOTC and ICAT required forms for stock assessment and control of quotas
# AI usage disclosure

No generative AI tools were used in the development of this software, the writing
of this manuscript, or the preparation of supporting materials.

# Acknowledgements

# References
